# _config_de.yml

lang: de
title: Monumental Movement
baseurl: "/de"
url: "https://monumental-movement.jp"

# 投稿ディレクトリ
collections:
  posts:
    output: true
    permalink: /de/:title/

# 出力フォルダ指定（既存の _site に上書きされないよう注意）
destination: ./_site/de

# plugins など共通設定は読み込み
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: de
      permalink: /de/:title/

# タグ・カテゴリ共通
tag_dir: tag
category_dir: category
