name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Add Linux platform to Gemfile.lock
        run: |
          bundle config set frozen false
          bundle lock --add-platform x86_64-linux

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build


      - name: Cache Jekyll build output
        uses: actions/cache@v3
        with:
          path: _site
          key: ${{ runner.os }}-site-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-site-

      - name: Build site (incremental)
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --incremental

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
